<?php

namespace Erazr\Bundle\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommmentRepository extends EntityRepository
{
}
