<?php

namespace Erazr\Bundle\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;


/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
	public function findNotifByUseType($destinataireId, $type)
    {
       return $this->createQueryBuilder('n')
        ->where('n.destinataire = :destinataireId')
        ->andwhere('n.type = :type')
        ->setParameter('destinataireId', $destinataireId)
        ->setParameter('type', $type)
	    ->getQuery()
        ->getResult();
    }
}
