<?php

namespace Erazr\Bundle\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	public function findAllPostOrderedByDate($order = 'desc')
    {
       return $this->createQueryBuilder('p')
		    ->orderBy('p.created', $order)
		    ->getQuery()
            ->getResult();
    }
	
	public function findAllPostOrderedByTimer()
    {
       return $this->createQueryBuilder('p')
        ->where('p.timer < :dateTimer')
        ->setParameter('dateTimer', new \DateTime('now'))
		    ->getQuery()
            ->getResult();
    }
}
