security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        hwi:
            id: erazr.oauth.user_provider
        P2:
            id: erazr_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            oauth:
                resource_owners:
                    facebook:      /login_facebook
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: erazr.oauth.user_provider
            form_login:
                provider:      fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me:   true
            logout: true
            anonymous: true

    access_control:
        - { path: ^/(top|login$), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/facebook, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
